# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: trailing-whitespace
        exclude_types:
          - "markdown"
      - id: end-of-file-fixer
      # - id: check-added-large-files
      #   args: ["--maxkb=10240"]
      # - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: ^\.vscode/.*\.json$
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: detect-private-key
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: forbid-new-submodules
      - id: mixed-line-ending
      #   - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.2"
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        language: system
        pass_filenames: false
        args: ["."]
