[project]
name = "setupwize"
version = "0.1"
description = ""
authors = [
  { name = "M.Abdulrahman Alnaseer", email = "20760062+abdalrohman@users.noreply.github.com" },
]
requires-python = ">=3.10,<=3.13"
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "click>=8.1.7",
    "python-dotenv>=1.0.1",
    "questionary>=2.0.1",
    "rich>=13.9.4",
    "tdqm>=0.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipython>=8.18.0",
    "pre-commit>=4.0.1",
]
codespell = [
    "codespell>=2.3.0",
]
linting = [
    "ruff>=0.8.3",
]
typing = [
    "mypy>=1.13.0",
    "types-decorator>=5.1.8.20240310",
    "types-pyyaml>=6.0.12.20240917",
    "types-six>=1.17.0.20241205",
]
